version: '3'
services:
  postgres:
    image: postgres
    container_name: my_app_psql
    ports:
      - 5432:5432
    env_file:
      - ./.env_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
  web:
    build: .
    container_name: my_app_flask
    restart: always
    volumes:
      - .:/usr/app/
    ports:
      - "5000:5000"
    command:
      "gunicorn --bind 0.0.0.0:5000 wsgi:app"
    env_file:
      - ./.env
    depends_on:
      - postgres
  nginx:
    image: nginx:mainline-alpine
    container_name: my_app_nginx
    depends_on:
        - web
    volumes:
        - ./nginx-conf/production:/etc/nginx/conf.d
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
    ports:
        - 80:80
        - 443:443
    logging:
      driver: json-file
  certbot:
    image: certbot/certbot
    container_name: my_app_cert
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
    postgresdata:
     
