version: '3'
services:
  postgres:
    image: postgres
    container_name: my_app_psql
    ports:
      - 5432:5432
    env_file:
      - ./.env_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
  web:
    build: .
    container_name: my_app_flask
    restart: always
    volumes:
      - .:/usr/app/
    ports:
      - "5000:5000"
    command:
      "python3 run.py"
    env_file:
      - ./.env
    depends_on:
      - postgres
  nginx:
    image: nginx:mainline-alpine
    container_name: my_app_nginx
    depends_on:
        - web
    volumes:
        - ./nginx-conf/local:/etc/nginx/conf.d
    ports:
        - 80:80
        - 443:443
    logging:
      driver: json-file
volumes:
    postgresdata:
